debug errors
need to be fix:
searchProfile() function
searchPosts() function
onLogout() function
pagination  for post  and profiles must show only 12 items
pagination on home is not loaded

Error: Element with id "getAllProfiles" not found in the DOM.